### ISSUE TITLE
can't connect anymore

### ISSUE THREAD

**Issue by theoneandonly-vector** [tristandostaler/EmpireGUI#3]
I can't connect to empire anymore (empire 1.6.0 and latest EmpireGUI)

java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-3
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.stage.Stage.<init>(Stage.java:241)
	at javafx.stage.Stage.<init>(Stage.java:227)
	at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
	at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
	at javafx.scene.control.Dialog.<init>(Dialog.java:263)
	at javafx.scene.control.Alert.<init>(Alert.java:245)
	at javafx.scene.control.Alert.<init>(Alert.java:223)
	at pse_gui.ResponseHandler.showOutput(ResponseHandler.java:70)
	at pse_gui.ResponseHandler.handleResponse(ResponseHandler.java:45)
	at pse_gui.RequestRunner.run(PowershellEmpireConnection.java:277)
	at pse_gui.PowershellEmpireConnection.send(PowershellEmpireConnection.java:141)
	at pse_gui.RequestHandler.getStagers(RequestHandler.java:156)
	at pse_gui.MainView$14$1.call(MainView.java:596)
	at pse_gui.MainView$14$1.call(MainView.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javafx.concurrent.Service.lambda$null$6(Service.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tristandostaler** [comment]
You tried with the username and password? it's an issue in Empire. Try with the token directly as explained here: 
https://github.com/tristandostaler/EmpireGUI/issues/1

If it is a duplicate, please close the issue. Thanks!

**Comment by tristandostaler** [comment]
It may also be that you are using empire 2.0_beta?
the empire 2.0_beta is buggy and the REST API doesn't work.

**Comment by tristandostaler** [comment]
Let me try with 1.6.0 and come back to you.

Thanks by the way!

**Comment by tristandostaler** [comment]
It worked for me with latest EmpireGUI and Empire 1.6.0. 
Maybe the token changed?
Can you try again and provide the past events output (don't forget to remove sensitive data)?

Thanks!

**Comment by theoneandonly-vector** [comment]
I just removed Empire and EmpireGUI and git cloned them again + run the initial setup for Empire.
It won't work using the API token. via terminal Empire works without a problem.
![empire](https://cloud.githubusercontent.com/assets/10380051/19957878/bca7d146-a19a-11e6-91e1-d61c92ce6e00.png)
![empiregui1](https://cloud.githubusercontent.com/assets/10380051/19957880/c07e6ece-a19a-11e6-9829-81d666adb8f9.png)
![empiregui_error](https://cloud.githubusercontent.com/assets/10380051/19957882/c489920a-a19a-11e6-9936-7a1366594b8b.png)

**Comment by theoneandonly-vector** [comment]
no Address an Port selected.
I just was confused, why EmpireGUI showed me: stagers, modules, agents -Menu's

**Comment by tristandostaler** [comment]
Hum excellent point! I will try to fix that some way soon. Thanks!!

**Comment by tristandostaler** [comment]
Hey! I added a few check for the login and changed the error displayed so you get something usefull for a error message. Check the new version!
Thanks again!
